### ISSUE TITLE
The Release step is not running

### ISSUE THREAD

**Issue by cr2007** [aerabi/hacktoberfest-cv#6]
I came here after seeing your [**video**](https://www.youtube.com/watch?v=DMwbXN3QKbs&t=550s) on the Docker YouTube channel.

I followed the same steps as mentioned, including adding the entire YAML file in mine.
But for some reason, the Release step in the workflow is skipped and it completes the workflow.
You can see from the screenshot below:
<img width="60%" alt="image" src="https://github.com/aerabi/hacktoberfest-cv/assets/73425927/e13d5df5-1f88-4f97-b0ae-773b03687ba4">

Here is the repository that I am using: https://github.com/cr2007/CV/

Is there any extra steps that I'm supposed to do to make this work?

**Comment by cr2007** [comment]
**Update:** I tried using the [**`git tag`**](https://git-scm.com/docs/git-tag) command and use the release tags on it, but upon pushing it back to GitHub, it gives this following error for the Release step:

<img width="55%" alt="image" src="https://github.com/aerabi/hacktoberfest-cv/assets/73425927/6a6ad5f0-651a-4195-a106-a385d9952a55">

**Comment by cr2007** [comment]
I fixed the issue!

You apparently have to go to the repository settings and enable Write Access for GitHub Actions.

The release feature now works, thank you so much!

Feel free to give any feedback/suggestions on improving the repository!
https://github.com/cr2007/CV

**Comment by cr2007** [comment]
Sure, I'll add it in the repo.

I'll reopen this issue so that I can associate it in a future PR

**Comment by aerabi** [comment]
Closed by #7.
